# Generated by Django 2.1 on 2018-10-22 15:05

from django.db import migrations

def populate_two_students(apps, schema_editor):
    # We can't import the Student model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Student = apps.get_model('requests', 'Student')
    student_one = Student.objects.create(first_name="John", 
                                         second_name="Doe")
    student_two = Student.objects.create(first_name="Lewis", 
                                         second_name="Smith")

    print(f"Populated two students... {student_one} and {student_two}")

def populate_two_corresponding_cards(apps, schema_editor):
    Nfc_card_model = apps.get_model('requests', 'NFCCard')
    card_one = Nfc_card_model.objects.create(card_id=34543534333)
    card_two = Nfc_card_model.objects.create(card_id=34534534535)

    print(f"Populated two cards... {card_one} and {card_two}")

class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_two_students),
        migrations.RunPython(populate_two_corresponding_cards)
    ]
