# Generated by Django 2.1.2 on 2018-11-03 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20181103_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_firstname', message='First name needs to only contain standard letters.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='second_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_secondname', message='Second name needs to only contain standard letters.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_firstname', message='First name needs to only contain standard letters.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_secondname', message='Second name needs to only contain standard letters.', regex='^[a-zA-Z]+$')]),
        ),
    ]
