# Generated by Django 2.1 on 2018-10-23 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_populate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfccard',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='nfc_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.NFCCard'),
        ),
    ]
