# Generated by Django 2.1.2 on 2018-11-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20181103_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.Event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.Student')),
            ],
        ),
    ]
