# Generated by Django 2.1 on 2018-10-23 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20181023_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nfc_card',
        ),
        migrations.AddField(
            model_name='nfccard',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.Student'),
        ),
    ]
