# Generated by Django 2.1 on 2018-11-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_auto_20181023_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the event', verbose_name='Date of the event')),
                ('start_time', models.DateField(help_text='Starting time', verbose_name='Starting time')),
                ('end_time', models.DateField(help_text='End time', verbose_name='End time')),
                ('notes', models.DateField(help_text='Event notes or comments', verbose_name='Event notes or comments')),
            ],
        ),
    ]
