# Generated by Django 2.1 on 2018-11-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_auto_20181102_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.Student'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='YYYY:MM:DD', verbose_name='Date of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(help_text='HH:MM', verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(help_text='HH:MM', verbose_name='Starting time'),
        ),
    ]
