# Generated by Django 2.1 on 2018-11-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_auto_20181102_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(to='requests.Student'),
        ),
    ]
