# Generated by Django 2.1.2 on 2018-12-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_auto_20181205_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfccard',
            name='card_id',
            field=models.IntegerField(unique=True),
        ),
    ]
