# Generated by Django 2.1.2 on 2018-12-13 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_auto_20181205_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
