# Generated by Django 2.1.2 on 2019-02-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_attendance_scanned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(default='null@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
