# Generated by Django 2.1.2 on 2019-02-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0012_lecturer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfccard',
            name='card_id',
            field=models.CharField(max_length=21, unique=True),
        ),
    ]
